[options]
admin_passwd = $pbkdf2-sha512$600000$f2/tHcOY8z7HGIMwxphTCg$hY2Cs.zvG12DF55fb4nqhwDASnkOThsWuxAFFILKKIP9LkWbN8VX5VTA9FmvNO9DAAjBOW9asg.ljXJV4q6oGw
addons_path = addons/extend_oca,addons/extend_third,addons/more_standard,addons/more_special,addons/more_trade,addons/tmp_pre,addons/tmp_sho,addons/tmp_test,addons/tmp_tmp,addons_dev/dev_a,addons_dev/dev_b,addons_dev/dev_c,addons_dev/dev_d,addons_dev/dev_e,addons_dev/dev_f,addons_dev/dev_k
auto_reload = True
bin_path = D:\Program Files\Odoo16.0\thirdparty
csv_internal_sep = 
data_dir = E:\www\w_pro\w_pro_uperp\pro_uperp\codes\v1.0\v1.0.0_uperp16\storage\odoo
dev_mode = all
db_host = localhost
db_maxconn = 64
db_name = False
db_user = erp_db
db_password = 123456
db_port = 3308
db_sslmode = prefer
db_template = template0
dbfilter = dev_up16_v1_.*
http_port = 9323
log_level = info
logfile = E:\www\w_pro\w_pro_uperp\pro_uperp\codes\v1.0\v1.0.0_uperp16\storage\log\up.log
pg_path = E:\wnpp\PostgreSQL13\bin
screencasts = 
screenshots = E:\www\w_pro\w_pro_uperp\pro_uperp\codes\v1.0\v1.0.0_uperp16\storage\odoo_tests
server_wide_modules = base,web

