[options]
admin_passwd = $pbkdf2-sha512$600000$GUNIKWWM0fqfM4YQAuB8Dw$/ymu/q.h9iQqFBUvK.MazVS4yCJ9qZtP2KDOZ9.aZO4RBJbaHtVLrHisL/ll6FSCo3Xq43NdSVRAUprqEIXieg
addons_path = odoo/addons,addons/extend_oca,addons/extend_third,addons/standard,addons/trade,addons/special,addons/tmp_pre,addons/tmp_test,addons/tmp_tmp
bin_path = /home/www/w_pro/pro_abcerp/codes/v1/v1.0_abcerp16/storage/thirdparty
csv_internal_sep = 
data_dir = /home/www/w_pro/pro_abcerp/codes/v1/v1.0_abcerp16/storage/odoo
db_host = 127.0.0.1
db_maxconn = 64
db_name = False
db_user = erp_db
db_password = PWD_0825
db_port = 3308
dbfilter = sho_abc16_v1_%d.*
;dbfilter = dev_v1_abcerp16_%d.*
http_port = 9515
log_level = info
logfile = /home/www/w_pro/pro_abcerp/codes/v1/v1.0_abcerp16/storage/log/abcerp.log
proxy_mode = True

